const CONSTANTES = {
  PRUEBA_UNO: 'PRUEBA_UNO',
  PRUEBA_DOS: 'PRUEBA_DOS',
  GET_ARTICULOS: 'GET_ARTICULOS',
  GET_ARTICULOS_CATEGORIA: 'GET_ARTICULOS_CATEGORIA',
  GET_ARTICULO_SLUG: 'GET_ARTICULO_SLUG',
  AGREGAR_ARTICULOS_STORE: 'AGREGAR_ARTICULOS_STORE',
  GET_ARTICULO: 'GET_ARTICULO',
};

export default CONSTANTES;
